version: '3'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: fx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Afin@2000
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    
  backend:
    depends_on:
      - db
    build:
      context: ./backend
    image: django-backend:latest
    container_name: django-backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:Afin@2000@db:5432/fx
    volumes:
      - ./backend/staticfiles:/app/staticfiles

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
